### ISSUE TITLE
Čtenář - zobrazení, vyhledávání

### ISSUE THREAD

**Issue by JanNovotny163** [RSP-TMP/LogosPolytechnikos#2]
#1 e752d2c

Testování proběhlo úspěšně

Pár dodatků:

1) Řazení časopisů podle data, názvu, ID chybí

2) Mohlo by se vyhledávat i při písemných chybách, například:
Název je "casopis2", vyhledá mi to i "časopis2" ale při zadání "casopis 2" už nevyhledá

3) Textbox, kde se zadává vyhledávání, by se mohl mazat automaticky, při kliknutí zůstává text "Zadejte název časopisu"

**Comment by MichalVachoVSPJ** [comment]
1. vyhledávání podle id nebude, id je skryto, řazení je naplánováno do jiného sprintu
2. mezeru nelze odstraňovat, jinak nelze hledat, mezery záleží na tom jak bude nastaven název časopisu
3. opraveno
