### ISSUE TITLE
Seznam článků

### ISSUE THREAD

**Issue by JanNovotny163** [RSP-TMP/LogosPolytechnikos#5]
1. Náhled dokumetnu - error NotFoundHttpException

**2. Filtrování**
2.1) Při filtrování datumu bych měsíce udělal jako čísla, pro lepší přehlednost, když seznam je vypisován např. 12.10.2020
2.2) Když zadám filtrování měsíce Listopad, vypíše i články z jiných měsíců
2.3) Při filtrování datumu se vždy ukáže text "This value is not valid"
2.4) Přijde mi navíc kolonka filtrování Autora, když by měl kontrolovat jen své příspěvky
2.5) Příliš mnoho filtrovacích políček, které seznam ani neukáže

3. Tlačítko nesouhlas - error NotFoundHttpException
4. Tlačítko Show - View článek bych vycentroval, nebo justify, začátek textu nejde vidět
5. Tlačítka Previous, číslo stránky a Next, po najetí bych udělal kurzor ruky

**Comment by jeline22** [comment]
Žádnou chybu NotFoundHttpException mě to nevyhazovalo. Problém není ve vývoji, ale spíš na tom že když si chtěl prohlédnout dokument tak ten dokument nebyl v tvém PC, jelikož nebyl pushnut na github, takže ti to symfony nemohlo najít, proto NotFoundHttpException.

Filtrování nebylo v rámci user storky řešeno, jen je tam připraveno rozhraní, které je vygenerované. Vývoj toho se řeší až v dalším sprintu.

Tlačítko pro nesouhlas jelikož tento vývoj není dokončený a bude se dělat zítra.

S show tlačítkem se musíme domluvit na meetingu co budeme s tímto typem zobrazení dělat a co přesně bude relevantní zobrazovat.
